language: go

notifications:
  email: false

matrix:
  include:
    # "1.x" always refers to the latest Go version, inc. the patch release.
    # e.g. "1.x" is 1.11 until 1.11.1 is available.
    - go: 1.x
      env: LATEST=true
    - go: 1.13.x
    - go: tip
  allow_failures:
    - go: tip

before_install:
  # gox simplifies building for multiple architectures
  - go get github.com/mitchellh/gox

install:
  - # skip

script:
  - go get -t -v ./...
  - diff -u <(echo -n) <(gofmt -d .)
  - go vet $(go list ./... | grep -v /vendor/)
  - go test -v -race ./...
  # Only build binaries from the latest Go release.
  - if [ "${LATEST}" = "true" ]; then gox -os="linux openbsd freebsd netbsd" -osarch="darwin/amd64 darwin/386" -ldflags "-X main.Rev=`git rev-parse --short HEAD`" -verbose ./...; fi

deploy:
  provider: releases
  api_key:
    secure: ExEGXZHm7Rald1Gh+AvnZibKRefZVufj6mKQ1dw8hg7hhYzZFRWLzx84VZOfmuhGpiGqGF+AEq1Z6w2sM1PiOblf3tvfHclpAn6BmMMzxTVZuPTC6wez62nXUBEAtg14+l5XCS4EUaEFLtIh2i1cgC6+PwoHR1cB04L8jAdtW3GI5cSS33gXyszxO5in1fqcSR8KxmUpy5xrD17YLUc2YqcDS4/BlrrrVsEbC+2U4aA6Kuw94CvrJ+1Y87XpxcssLu6wb8aT8L22QKwRk63EHgLfVqQ2NwPltzBRgh+Sf4cyyOqvOI+PgX3hHCH8wa3Hsage9UNnUbj3wPRzTzWQ9Huk6UEefymrqzR/ErJ6ySZzWmsVYeXo18rqyuSLLzf5K31J3rbZ0mjiNrSjxh7IkS+yYsDd7uDEibrI598fg+9XWouYiuapkS05ZNMxI2hmY2rlvxnG/wt2iewQAvuGDIxozSvVlskmbtvSbgSjI7R5cXhN14tI263RA+uC4MP4n4O2/hZIS/GlR7pJR+yiDVRKPOmLyoU2iT5Nfxmy92OdoNUd7j44qptSc6lwCOwN/KNgh4g/0LDXB3gnm2F1/vlmVOK46UEVpdzKDOulPK9eSFbqyjW97mtQcGr8B9Ue6hjddXwjMYyQzn4Xl+OTDvdBOEm4dX9GF3EWg0Uza9I=
  file_glob: true
  file:
    # The names of the binaries to output, based on the -output template passed to gox.
    - Gope_*
  on:
    repo: notmeta/Gope
    tags: true
    condition: $LATEST = true
  skip_cleanup: true
