# This is a TOML document. Boom.

title = "Database backup"
description = "Used to backup the database using the sql dump command"

[tasks]

  [tasks.test]
  command = "docker fsdafe || exit 3"
  interval = "* * * * *"

  [tasks.test2]
  command = "docker ps"
  interval = "* * * * *"