title = "Database backup"
description = "Used to backup the database using the sql dump command"
printOnFinish = false

[tasks]

  [tasks.test]
  command = "docker fsdafe"
  interval = "* * * * *"
  timeout = 120

    [tasks.test.retry]
    codes = [1, 3]
    tries = 20
    delay = 4
    maxDelay = 10
    backoff = 1.1

    [tasks.test.onexit.0]
    command = "echo nothing to report"

    [tasks.test.onexit.1]
    command = "echo invalid command!"

    [tasks.test.onexit.3]
    command = "echo help, I just exited incorrectly!"
