title = "Database backup"
description = "Used to backup the database using the sql dump command"
printOnFinish = false

[tasks]

      [tasks.check_docker_processes]
      command = "docker ps"
      interval = "* * * * *"
#      timeout = 10

        [tasks.check_docker_processes.onexit.0]
        log = "Nothing to report"

    [tasks.bad_command]
    command = "docker images"
    interval = "* * * * *"

    [tasks.bad_command.retry]
    codes = [127]
    tries = 20
    delay = 3
    maxDelay = 10
    backoff = 1.1

    [tasks.bad_command.onexit.0]
    log = "Nothing to report"

    [tasks.bad_command.onexit.127]
    log = "echo invalid command!"

    [tasks.bad_command.onexit.3]
    log = "echo help, I just exited incorrectly!"

