# This is a TOML document. Boom.

title = "Database backup"
description = "Used to backup the database using the sql dump command"

[tasks]

  [tasks.test]
  command = "docker ps && exit 2"
  interval = "00 10 * * *"
